### ISSUE TITLE
Not getting package environment when using testthat::test_file

### ISSUE THREAD

**Issue by kjohnsen** [krlmlr/mockr#3] opened 2018-06-21 01:44 UTC
In my package I have a test file `tests/testthat/test_my_func.R`:

```r
context('Testing my_func')

.mock_slow_func <- function() { 42 }

test_that('my_func works', {
  result <- mockr::with_mock(.slow_func=.mock_slow_func,
                             my_func())
  expect_equal(result, list(answer=42))
})
```

`my_func` and helper function `.slow_func` are defined in the package as follows:
```r
.slow_func <- function() { return(6 * 7) }
my_func <- function() { return(list(answer=.slow_func())) }
```

I was using `testthat:with_mock()`, and I could call `testthat::test_file('tests/testthat/test_my_func.R)` with no problem. Now that I've switched to mockr, I get the following error when using `test_file`:

```r
test_my_func.R:6: error: my_func works
.slow_func not found in environment R_GlobalEnv.
1: mockr::with_mock(.slow_func = .mock_slow_func, my_func()) at tests/testthat/test_my_func.R:6
2: with_mock_(.dots = .dots, .parent = .parent, .env = .env)
3: create_mock_env_(.dots = get_mock_dots(dots), .env = .env, .parent = .parent)
4: extract_new_funcs_(dots, .env)
5: extract_mocks(dots = dots, env = .env)
6: lapply(stats::setNames(nm = names(dots)), function(qual_name) extract_mock(qual_name, dots[[qual_name]], 
       env))
7: FUN(X[[i]], ...)
8: extract_mock(qual_name, dots[[qual_name]], env)
9: check_mock(name, env)
10: stopc(name, " not found in environment ", environmentName(env), ".")
11: stop(..., call. = FALSE, domain = NA)
```

It seems to me that where `testthat::with_mock` would use the package environment, `mockr::with_mock` does not (it searches `R_GlobalEnv` instead), which is annoying when I want to run just one test file.

**Comment by kjohnsen** [comment] 2018-06-21 01:54
### Suspicion confirmed

I change the test like this and it works fine:
```r
test_that('my_func works', {
  result <- mockr::with_mock(.slow_func=.mock_slow_func,
                             my_func(),
                             .env=as.environment('package:test'))
  expect_equal(result, list(answer=42))
})
```

#### test passes
`testthat::test_file('tests/testthat/test_my_func.R')`

**Comment by krlmlr** [comment] 2020-12-13 07:17
Thanks, I've seen this elsewhere too. Need to look into it.

**Comment by krlmlr** [comment] 2020-12-15 06:18
Is this a duplicate of #4?

**Closed** 2020-12-15 07:22 UTC
